theme: jekyll-theme-cayman
title: "UiTM Kedah Statistical Service Unit"

# NAVIGATION
#====================================
navigation:
  - name: Blog
    url: /	
  - name: Projects
    url: /projects
  - name: About
    url: /about
#  - name: Archive
#    url: /archive
#  - name: Tags
#    url: /tags
