theme: jekyll-theme-cayman
title: "UiTM Kedah Statistical Service Unit"

#
#   Navigation to the left › side: left
#
- title: "Home"
  url: "/"
  side: left
  
- title: "About Us"
  url: "/about/"
  side: left
  dropdown:
  - title: "What is Dublin CSA?"
    url: "/about/dublin-csa/"
  - title: "How it works"
    url: "/about/how-it-works/"
  - title: "Pricing"
    url: "/about/pricing/"
  - title: "Our Growers"
    url: "/about/growers/"
  - title: "FAQ's"
    url: "/about/faq/"
    
- title: "Join"
  url: "/join/"
  side: left

- title: "Community News"
  url: "/news/"
  side: left
  
- title: "Recipies"
  url: "/recipies/"
  side: left
  
- title: Events
  url: "/events/"
  side: left
  dropdown:
  - title: "Farm days"
    url: "/events/farm-days/"
  - title: "Meet the CSA"
    url: "/events/meet-csa/"
  - title: "Annual Meeting"
    url: "/events/annual-meeting/"

#
#   Navigation to the right › side: right
#
- title: "Search"
  url: "/search/"
  side: right

- title: "Contact"
  url: "/contact/"
  side: right
